/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.gradle.project;

import java.io.IOException;
import com.github.dtmo.jfiglet.FigFontResources;
import com.github.dtmo.jfiglet.FigletRenderer;
import com.mitchtalmadge.asciidata.graph.ASCIIGraph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        // String graph = ASCIIGraph.fromSeries(new double[] { 1.0, 2.0, 3.0, 10.0, 7.0,
        // 9.0, 5.0, 4.0 }).plot();
        // System.out.println(graph);

        FigletRenderer figletRenderer;
        try {
            figletRenderer = new FigletRenderer(FigFontResources.loadFigFontResource(FigFontResources.BIG_FLF));
            System.out.println(figletRenderer.renderText("DevOps rocks"));
            System.out.println(figletRenderer.renderText("und unser Team auch :)"));
            System.out.println(figletRenderer.renderText("Aller guten Dinge sind drei."));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }        
    }
}
